# This is a basic workflow to help you get started with Actions

name: CI xgxaliyun

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ] 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Aliyun
        run: docker login --username=${{ secrets.ALIYUN_USERNAME }} --password=${{ secrets.ALIYUN_PASSWORD }} registry.cn-hangzhou.aliyuncs.com

      #-
        #name: Build 
        #run: docker build . --file Dockerfile --tag registry.cn-hangzhou.aliyuncs.com/deadlessbird/deadlessbirdxgx:simplewale-latest
      
      -
        name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: registry.cn-hangzhou.aliyuncs.com/deadlessbird/deadlessbirdxgx:simplewale-latest-0.0.9